#ServerPort
server:
  port: 8001

#DataSource
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@metaverse.ohgiraffers.com:1521/xe
    username: C##LEISURETHAT_TEST
    password: LEISURETHAT
#    url: jdbc:oracle:thin:@leisurethat_low?TNS_ADMIN=./src/main/resources/Wallet_leisurethat
#    username: LEISURETHAT
#    password: OracleOracle123
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/dykim/Downloads
  config:
    import: classpath:application-aws.yml

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error


jwt:
  header: Authorization
  secret: leisurethatthatthatleisure
  access-token-validity-in-seconds: 7200 #2 hours
  refresh-token-validity-in-seconds : 43200 # 12 hours

