#ServerPort
server:
  port: 8001

#DataSource
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##leisurethat
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/dykim/Downloads
  config:
    import: classpath:application-aws.yml

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error

jwt:
  header: Authorization
  secret: leisurethatthatthatleisure
  access-token-validity-in-seconds: 7200 #2 hours
  refresh-token-validity-in-seconds : 43200 # 12 hours

#Toss Secret Key
key:
  SECRET: "test_sk_D4yKeq5bgrpmoOaRLyX8GX0lzW6Y:"
  CUSTMER: "test_ck_7DLJOpm5Qrl2BpO2oKe3PNdxbWnY"
