#ServerPort
server:
  port: 8001

#DataSource
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@leisurethat_high?TNS_ADMIN=./src/main/resources/Wallet_leisurethat
    username: LEISURETHAT
    password: OracleOracle123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/dykim/Downloads

#JWT Token
jwt:
  header: Authorization
  secret: leisurethatthatthatleisure
  access-token-validity-in-seconds: 7200 #2 hours
  refresh-token-validity-in-seconds : 43200 # 12 hours

#Toss Secret Key
key:
  SECRET: "test_sk_D4yKeq5bgrpmoOaRLyX8GX0lzW6Y:"